[package]
name = "cheshire-cats"
version = "0.1.0"
edition = "2024"
authors = [
	"Anthony Greenberg <info@bayesicresearch.org>",
	"Andrew Walker <andrew.walker@earth.ox.ac.uk>",
]
license = "MIT"

[workspace]
members = ["slurm-sys"]

[dependencies]
slurm-sys = { path = "slurm-sys" }
clap = { version = "4.6", features = ["derive"] }
env_logger = "0.11"
jiff = "0.2"
libc = "0.2"
log = "0.4"
signal-hook = "0.4"
