//! Raw bindings to libslurm, generated by bindgen at build time.
//!
//! Only the node-query, node-update and hostlist calls cheshire-cats needs are
//! bound. The `NODE_STATE_*` flags are taken from the installed headers rather
//! than hard-coded, because Slurm recycles flag bits between releases.

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
