//! Locates the libslurm install and generates bindings against its headers.
//!
//! Build against the libslurm that matches the cluster's slurmctld:
//!
//!   SLURM_PREFIX=/opt/slurm cargo build
//!
//! `SLURM_INCLUDE_DIR` and `SLURM_LIB_DIR` override the two halves of the
//! prefix separately. With nothing set, `/usr` is assumed.

use std::env;
use std::path::{Path, PathBuf};

fn main() {
    for var in ["SLURM_PREFIX", "SLURM_INCLUDE_DIR", "SLURM_LIB_DIR"] {
        println!("cargo:rerun-if-env-changed={var}");
    }
    println!("cargo:rerun-if-changed=wrapper.h");

    let prefix      = PathBuf::from(env::var("SLURM_PREFIX").unwrap_or_else(|_| "/usr".into()));
    let include_dir = env::var("SLURM_INCLUDE_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| prefix.join("include"));
    let lib_dir = env::var("SLURM_LIB_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| default_lib_dir(&prefix));

    // slurm_version.h is generated by Slurm's configure, so a bare source
    // checkout does not have it. Catch that here with a readable message.
    let version_h = include_dir.join("slurm/slurm_version.h");
    if !version_h.exists() {
        panic!(
            "{} not found; point SLURM_PREFIX (or SLURM_INCLUDE_DIR) at an installed libslurm",
            version_h.display()
        );
    }

    println!("cargo:rustc-link-search=native={}", lib_dir.display());
    println!("cargo:rustc-link-lib=dylib=slurm");
    // Exposed to dependents as DEP_SLURM_LIB_DIR so the binary can set an rpath.
    println!("cargo:lib_dir={}", lib_dir.display());

    let bindings = bindgen::Builder::default()
        .header("wrapper.h")
        .clang_arg( format!( "-I{}", include_dir.display() ) )
        // NODE_STATE_* flags are SLURM_BIT(n), a function-like macro that
        // bindgen only evaluates with this fallback enabled.
        .clang_macro_fallback()
        .allowlist_function("slurm_init")
        .allowlist_function("slurm_fini")
        .allowlist_function("slurm_load_node")
        .allowlist_function("slurm_free_node_info_msg")
        .allowlist_function("slurm_init_update_node_msg")
        .allowlist_function("slurm_update_node")
        .allowlist_function("slurm_strerror")
        .allowlist_function("slurm_hostlist_(create|shift|destroy)")
        .allowlist_type("node_states")
        .allowlist_var("NODE_STATE_.*")
        .allowlist_var("NODE_RESUME")
        .allowlist_var("NO_VAL")
        .allowlist_var("INFINITE")
        .allowlist_var("SHOW_ALL")
        .allowlist_var("SLURM_SUCCESS")
        .allowlist_var("SLURM_VERSION_STRING")
        .prepend_enum_name(false)
        .parse_callbacks( Box::new( bindgen::CargoCallbacks::new() ) )
        .generate()
        .expect("failed to generate libslurm bindings");

    let out = PathBuf::from( env::var("OUT_DIR").unwrap() ).join("bindings.rs");
    bindings
        .write_to_file(out)
        .expect("failed to write bindings");
}

/// RPM-based distributions install libslurm under lib64.
fn default_lib_dir(prefix: &Path) -> PathBuf {
    let lib64 = prefix.join("lib64");
    if lib64.join("libslurm.so").exists() {
        lib64
    } else {
        prefix.join("lib")
    }
}
